import type { Metadata } from "next";
import { Caudex, Averia_Serif_Libre, Prompt, Open_Sans, Forum } from "next/font/google";
import "./globals.css";
import CustomCursor from "./CustomCursor";
// import Footer from "@/Components/Common/Footer/page";

const promptFont = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const averiaSerif = Averia_Serif_Libre({
  variable: "--font-averia-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const caudexFont = Caudex({
  variable: "--font-caudex",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const bodoniModa = Forum({
  variable: "--font-bodoni-moda",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Darshan B | MERN & MEAN Stack Developer",
  description: "Generated by create next app",
  icons: {
    icon: "/img/favicon_io/favicon.ico",
    shortcut: "/img/favicon_io/favicon-32x32.png",
    apple: "/img/favicon_io/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${promptFont.variable} ${averiaSerif.variable} ${caudexFont.variable} ${openSans.variable} ${bodoniModa.variable} antialiased`}
      >
        <CustomCursor />

        {/* Header is rendered per-page (below Hero) */}
        {children}

        {/* <Footer /> */}
      </body>
    </html>
  );
}
