import type { Metadata } from "next";
import { Caudex, Averia_Serif_Libre, Prompt, Open_Sans } from "next/font/google";
import "./globals.css";
import CustomCursor from "./CustomCursor";
// import Footer from "@/Components/Common/Footer/page";

const promptFont = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const averiaSerif = Averia_Serif_Libre({
  variable: "--font-averia-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const caudexFont = Caudex({
  variable: "--font-caudex",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Darshan B | MERN Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${promptFont.variable} ${averiaSerif.variable} ${caudexFont.variable} ${openSans.variable} antialiased`}
      >
        <CustomCursor/>
        {/* Header is rendered per-page (below Hero) */}
        {children}

        {/* <Footer /> */}
      </body>
    </html>
  );
}
